apiVersion: v1
kind: Service
metadata:
  name: user-service-db
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-service-db
  ports:
    - name: pg
      port: 5432
      targetPort: 5432