apiVersion: v1
kind: Service
metadata:
  name: order-service-db
  namespace: {{ .Values.global.namespace }}
  labels:
    app: order-service-db
spec:
  type: ClusterIP
  selector:
    app: order-service-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432