apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: authentication-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
