apiVersion: v1
kind: Service
metadata:
  name: payment-service-db
  namespace: {{ .Values.global.namespace }}
  labels:
    app: payment-service-db
spec:
  type: ClusterIP
  selector:
    app: payment-service-db
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017