apiVersion: v1
kind: Secret
metadata:
  name: authentication-service-db-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: "postgres"
  password: "12345"
  database: "auth_db"