apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authentication-service-db
  namespace: {{ .Values.global.namespace }}
  labels:
    app: authentication-service-db
spec:
  serviceName: authentication-service-db
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service-db
  template:
    metadata:
      labels:
        app: authentication-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: authentication-service-db-secrets
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authentication-service-db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-service-db-secrets
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi