apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087